### ISSUE TITLE
Implement IteratorAggregate

### ISSUE THREAD

**Issue by solleer** [Level-2/Maphper#39]
@TomBZombie We were talking about removing the `item` function and the problems with filter. I was wondering if we should have Maphper implement IteratorAggregate instead of Iterator. The only function that uses the array property other than implementing the iterator is the `item` function. I think refactoring the iterator functionality into a separate class would be good over all for SOC.

**Comment by TomBZombie** [comment]
I wasn't actually aware of IteratorAggregate, I really like that for SOC, yes that's definitely a good idea.

**Comment by solleer** [comment]
The main issue is the `item` function

**Comment by TomBZombie** [comment]
it's not quite that simple. The `key` function:

```
	public function key() {
		$pk = $this->dataSource->getPrimaryKey();
		$pk = end($pk);
		return $this->array[$this->iterator]->$pk;
	}


```

Poses a problem. For this:

```
foreach ($users as $id => $user) {

}
```

`$id` should probably be the PK but for


```
foreach ($user[123]->products as $id => $value) {

}
```

If we're removing `->item()` then `$id` should be index. What I want to avoid is direct key lookups e.g. `$user[123]` being primary key and `foreach ($user as $key => $value)` being index as it's terribly inconsistent. Despite being horribly inefficient, this should work:

```
foreach ($users as $id => $user) {
   echo $users[$id]->username;
}
```

Ideally PHP would let us do:

```
current($users)
```

Instead of `->item(0)`

**Comment by TomBZombie** [comment]
In theory we don't even need a custom iterator, we could do this:

```php
	public function getIterator() {
		$this->fillArrayValues();
		$this->array = array_map([$this, 'create'], $this->array);
		$this->array = array_map([$this, 'wrap'], $this->array);
		return new \ArrayIterator($this->array);
	}
```

(and remove the array property by making it a return value of fillArrayValues)

**Comment by solleer** [comment]
I like using current especially since item is usually used to access index 0. The problem is that I don't know of a solution that would work for both raw data and and iterators.

**Comment by TomBZombie** [comment]
With php 7.1's `iteratble` type hint it looks like PHP is heading that way. Hopefully iterators and arrays will be entirely interchangeable at some point. We could use `->current()` instead of `->item(0)` which at least makes it possible to type hint `Traversable` (or `iteratable` in PHP7.1) and not rely on anything that isn't part of the iterator interface. 

I'm going to add a feature request to bugs.php.net to allow current(), end() etc to work on an iterator.

**Comment by TomBZombie** [comment]
actually there already is one: https://bugs.php.net/bug.php?id=49369

**Comment by solleer** [comment]
So should the key be the index or the pk.

**Comment by solleer** [comment]
@TomBZombie What should be the key if it has multiple primary keys

**Comment by TomBZombie** [comment]
Perhaps we should keep it so indexes are always pk with a note to users that you cannot loop with a for loop because not all indexes will be set, so a for each loop will give pk as the key in any scenario. 

If we implement current/next it allows replacing the item function as most use cases are just to fetch the first entry.

For multi pks, $key should probably be an array

**Comment by solleer** [comment]
I am going to have maphper implement iterator aggregate and create a class to be the iterator. Also should it by index or pk for many and manymany

**Comment by TomBZombie** [comment]
For consistency it would be better to always use keys rather than indexes. The problem with doing that, though, is that you can't then replace maphper with json_decode, as that would give us either index based arrays or objects with keys. 

I'm not sure what the best answer is really, other than making maphper use array rather than object lookups and decoding json into an array... However, I don't really like that solution either

**Comment by solleer** [comment]
I think index might be best because besides being easiest to implement, since you have the data upon each iteration you always have the pk no matter what but currently you don't have the index too so getting both would give more options.

**Comment by TomBZombie** [comment]
The issue with index is that maphper uses pk for the root object, e.g. `$users[123]`, and that's not something we want to change. As I said above, this I consistency causes its own set of problems.

If json allowed specifying the keys for an array we wouldn't have this problem.

**Comment by TomBZombie** [comment]
if PHP was like javascript and didn't differentiate between objects and arrays we also wouldn't have this issue.

I suppose we could release a class like this:

```
<?php

class UniformAccess implements \ArrayAccess, \Countable {
	private $data;

	public function __construct($data) {
		$this->data = (array) $data;
	}

	public function offsetExists($offset) {
		return isset($this->data[$offset]);
	}

	public function offsetGet($offset) {
		return $this->data[$offset];
	}

	public function offsetSet($offset, $value) {
		$this->data[$offset] = $value;
	}

	public function offsetUnset($offset) {
		unset($this->data[$offset]);
	}

	public function __get($key) {
		$val = $this[$key];
		if (is_object($val) || is_array($val)) return new UniformAccess($val);
		else return $val;
	}

	public function __set($key, $value) {
		$this[$key] = $value;
	}

	public function current() {
		return current($this->data);
	}
}
```

Then replacing `maphper` with `json_decode` can be done using:

```
$maphper = new UniformAccess(json_decode($json));
```

And the json could look like this:

```
{
	"name": "Tom",
	"id": 3,
	"orders": {
		"175": {
			"total": "145.23",
			"tax": "34.6"
			"products": {
				"897": {
					"name": "Intel i7 7700k"
					"id": "897"
				},
				"34": {
					"name": "Nvidia 970",
					"id": "34"
				}
			}
		}
	}
}
```

as opposed to:

```
{
	"name": "Tom",
	"id": 3,
	"orders": [
			{
				"total": "145.23",
				"tax": "34.6"
				"products": [
					{
						"name": "Intel i7 7700k"
						"id": "897"
					},
					{
						"name": "Nvidia 970",
						"id": "34"
					}
				]
			}
		]
	}
}
```

Then when you could do this:

```
$users = new UniformAccess(json_decode('file.json'));

foreach ($users[123]->orders->current()->products as $key => $product) {
    echo $users[123]->products[$key]->name
}

```

Because we can use either `[]` or `->` notation to access the data, it's possible to load the list of products from the JSON file as an object with keys/values.

It's a bit of extra work for anyone who wants to do this, but JSON was invented for use in javascript where objects and arrays are interchangeable.

**Comment by TomBZombie** [comment]
And as an extension, we could give maphper the same feature so that  `$users[123]->name` and `$users[123]['name;']` are interchangeable.

**Comment by solleer** [comment]
So when accessing a manymany relationship as an array like `$actors[1]->movies[1]` should the index be pk or index

**Comment by TomBZombie** [comment]
For consistency it should always be pk. In most cases you'd either want to iterate over all the records or fetch the first, which we can provide `current()` for
