### ISSUE TITLE
Easy way to save updated item back to the right datasource?

### ISSUE THREAD

**Issue by pwFoo** [Level-2/Maphper#72]
Hi @TRPB,

update an item is easy with mapher...
```
$blogs[7] = $blog;
```
or 
```
$blog->id = 7;
$blogs[] = $blog;
```

But is it possible to load a item, change it and save it back to datasource without the need of to know the right datasource / maphper object?
```
$item = $blogs[142];

$item->title = "New title";
//$blogs[] = $item;   // working example, but I need the $blogs object
$item->save()  // how to do it for example with a custom item class?
```

**Comment by TRPB** [comment]
That would be the ActiveRecord pattern rather than Data Mapper which Maphper uses. It's a poor choice because the entity it coupled to the database, encapsulation is broken as the entity knows where it comes from and how it is going to be stored.

You could implement this yourself on a per-entity basis. Make the mapper a constructor argument and ad the save function.

There are various discussions about the pros/cons of activerecord and data mapper: https://www.thoughtfulcode.com/orm-active-record-vs-data-mapper/
http://jgaskins.org/blog/2012/04/20/data-mapper-vs-active-record

**Comment by pwFoo** [comment]
Save function would be easy, if I get the maphper reference. 
```
function save() {
    $dataSourceReference[] = $item
}
```
Right?

Found that example, but how can I use `$dataSource` in `use`?
```
$dataSource = new \Maphper\Maphper($database, ['resultClass' => function() use ($dataSource) {
	return new Product($dataSource); // need $dataSource here?
}]);
```

**Comment by TRPB** [comment]
You can do it with references:

[code]
$dataSource = new \Maphper\Maphper($database, ['resultClass' => function() use (&$dataSource) {
	return new Product($dataSource); // need $dataSource here?
}]);
[/code]
